name: Helm Upgraude
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Environment to deploy to"
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './kube2py/values.yaml'
      helm-release-name:
        required: true
        description: "Name of the helm release"
        default: kube2py
        type: string



jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: helm-package
        path: .

    - uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CRENDETIALS }}

    - uses: azure/aks-set-context@v3
      with:
        cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}
        resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

    - name: Deploy Helm
      run: |
        helm upgrade --install --atomic --debug ${{ inputs.helm-release-name }} ./kube2py-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set kube2py.secrets.password="${{ secrets.KUBE2PY_PASSWORD }}" \
          --set kube2py.secrets.login="${{ secrets.KUBE2PY_LOGIN }}" \
          --set kube2py.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
          --set global.environment="${{ inputs.environment }}" \
          --set kube2py.image.version="2.0.0"
